### PR TITLE
db obj store backup script.

### PR DESCRIPTION
**Pull request by sureshg**

### CODE REVIEW

**Comment by schwankl** [comment]
why isnt objectstore component being used?  cloudrdbms is using that and it already supports upload, download and delete

**Comment by schwankl** [comment]
https://github.com/oneops/circuit-oneops-1/blob/master/components/cookbooks/objectstore/files/default/objectstore

**Comment by sureshg** [comment]
Thanks! Here i want to add more validation and retry the upload in case of any error. The plan is to use this command instead of existing scp used in cronjob.

**Comment by schwankl** [comment]
still think you should reuse objectstore component and possibly enhance that instead of having this one-off script

**Comment by vitaliyzinchenko** [comment]
Suresh, Mike's comment makes sense, please use objectstore component, that way enhancements could be reused by the community

**Comment by sureshg** [comment]
Making the necessary changes to objstore component script. Closing this one.

**Pull request closed without merging**
